import "@/styles/globals.css";

import { type Metadata } from "next";

import Background from "./_components/background";
import Navigation from "./_components/navigation";

export const metadata: Metadata = {
  title: "Intania Tech Month 2024",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/techmonth/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <body className="bg-techmonth-black text-techmonth-white">
      <Navigation />
      <main className="-mt-[calc(100vh-14px)]">{children}</main>
      <Background />
    </body>
  );
}
