import "@/styles/globals.css";

import { type Metadata } from "next";

import Background from "./_components/background";
import Navigation from "./_components/navigation";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <body className="bg-techmonth-black text-techmonth-white">
      <Navigation />
      {children}
      <Background />
    </body>
  );
}
