import '~/styles/globals.css';

import { GoogleTagManager } from '@next/third-parties/google';
import { type Metadata } from 'next';
import { PublicEnvScript } from 'next-runtime-env';

import { Toaster } from '~/components/ui/toaster';
import { env } from '~/env';
import {
  geistMono,
  geistSans,
  ibmPlexSansThai,
  ndot47,
  pressStart2P,
  tiny5,
} from '~/lib/fonts';
import { cn } from '~/lib/utils';
import { TRPCReactProvider } from '~/trpc/react';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout: React.FC<Readonly<{ children: React.ReactNode }>> = ({
  children,
}) => {
  return (
    <html
      lang="en"
      className={cn(
        ibmPlexSansThai.variable,
        pressStart2P.variable,
        tiny5.variable,
        ndot47.variable,
        geistMono.variable,
        geistSans.variable,
      )}
    >
      <GoogleTagManager gtmId={env.NEXT_PUBLIC_GTM_ID ?? ''} />
      <head>
        <PublicEnvScript />
      </head>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
};

export default RootLayout;
