import '~/styles/globals.css';

import { type Metadata } from 'next';
import {
  IBM_Plex_Sans_Thai as IBMPlexSansThai,
  Press_Start_2P as PressStart2P,
} from 'next/font/google';
import localFont from 'next/font/local';

import { Toaster } from '~/components/ui/toaster';
import { cn } from '~/lib/utils';
import { TRPCReactProvider } from '~/trpc/react';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const pressStart2P = PressStart2P({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-press-start-2p',
});
const tiny5 = localFont({
  src: '../../public/techmonth/fonts/Tiny5-Regular.ttf',
  variable: '--font-tiny5',
});
const ibmPlexSansThai = IBMPlexSansThai({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-ibm-plex-sans-thai',
});

const RootLayout: React.FC<Readonly<{ children: React.ReactNode }>> = ({
  children,
}) => {
  return (
    <html
      lang="en"
      className={cn(
        pressStart2P.variable,
        tiny5.variable,
        ibmPlexSansThai.variable,
      )}
    >
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
};

export default RootLayout;
