import "@/styles/globals.css";

import { type Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import localFont from "next/font/local";
import { IBM_Plex_Sans_Thai } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const pressStart2P = Press_Start_2P({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-press-start-2p",
});
const tiny5 = localFont({
  src: "../../public/techmonth/fonts/Tiny5-Regular.ttf",
  variable: "--font-tiny5",
});
const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ibm-plex-sans-thai",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        pressStart2P.variable,
        tiny5.variable,
        ibmPlexSansThai.variable,
      )}
    >
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
