name: CD - Deploy to Kubernetes

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

env:
  GITOPS_REPO: esc-chula/tech-website-gitops
  GITOPS_DEPLOYMENT_PATH: base/deployment.yaml
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download Release Tag Artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: Release.yml
          workflow_conclusion: success
          name: release-tag
          path: .

      - name: Read Release Tag from Artifact
        id: get-release-tag
        run: echo "RELEASE_TAG=$(cat release_tag.txt)" >> $GITHUB_ENV

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update image tag in deployment.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers[0].image = "${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}"' gitops/${{ env.GITOPS_DEPLOYMENT_PATH }}

      - name: Commit and push changes to GitOps repo
        run: |
          cd gitops
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "build(deploy): Update deployment.yaml for ${{ env.RELEASE_TAG }}"
          git push
