name: CD - Deploy to Kubernetes

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

env:
  GITOPS_REPO: esc-chula/tech-website-gitops
  GITOPS_DEPLOYMENT_PATH: base/deployment.yaml
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Extract Release Tag
        run: echo "RELEASE_TAG=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update image tag in deployment.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers[0].image = "${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}"' gitops/${{ env.GITOPS_DEPLOYMENT_PATH }}

      - name: Commit and push changes to GitOps repo
        run: |
          cd gitops
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "build: Update ${{ env.GITOPS_DEPLOYMENT_PATH }} to ${{ steps.get-image-tag.outputs.image_tag }}"
          git push
