name: Release

on:
  workflow_dispatch:
    inputs:
      target:
        required: true
        description: New tag (Tag created by CI / Manual Version Bumping)

jobs:
  release_commit:
    name: Release commit
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: "blob:none"
          fetch-depth: 0

      # Update changelog
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: "--verbose --tag ${{ github.event.inputs.target }}"
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      # Update package.json
      - name: Update package.json
        run: |
          PACKAGEJSON=$(jq --indent 4 '.version = ("${{ github.event.inputs.target }}" | sub("v"; ""))' package.json)
          echo "$PACKAGEJSON" > package.json

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): prepare for ${{ github.event.inputs.target }}"

  release_github:
    name: Release github
    runs-on: ubuntu-latest
    needs: release_commit

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --unreleased --strip all --tag ${{ github.event.inputs.target }}
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGES.md
          tag_name: ${{ github.event.inputs.target }}